version: '3.8'

services:

  db:
    image: postgres:13-alpine
    container_name: postgres-13-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${DB_PASS:-ffrp}
      POSTGRES_USER: ${DB_USER:-user}
      POSTGRES_PASSWORD: ${DB_PASS:-pass}
