spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
          swissid:
            client-id: ${SWISSID_CLIENT_ID}
            client-secret: ${SWISSID_CLIENT_SECRET}
            scope: openid,profile,email
            redirect-uri: http://localhost:8080/login/oauth2/code/swissid
            client-name: swissid
            provider: swissid
            client-authentication-method: client_secret_basic
            authorization-grant-type: authorization_code
        provider:
          swissid:
            authorization-uri: https://login.sandbox.pre.swissid.ch:443/idp/oauth2/authorize
            token-uri: https://login.sandbox.pre.swissid.ch:443/idp/oauth2/access_token
            user-info-uri: https://login.sandbox.pre.swissid.ch:443/idp/oauth2/userinfo
            user-name-attribute: sub
            jwk-set-uri: https://login.sandbox.pre.swissid.ch:443/idp/oauth2/connect/jwk_uri
            user-info-authentication-method: header
  thymeleaf:
    cache: false
logging:
  level:
    org.springframework.security: TRACE
